
set -g prefix C-SPACE
# default
set -g base-index 1
set -g mode-keys vi
set -g default-terminal "xterm-ghostty"
set -as terminal-overrides ",xterm-256color:RGB"
# status
set -g status-position top
set -g status-style 'fg=#ffffff'
set -g status-left '[#S] '
set -g status-left-length 20
set -g status-right ''
set -g status-justify absolute-centre
# window
setw -g window-status-style 'fg=#888888'
setw -g window-status-current-style 'bg=#bae1ff,fg=#000000,bold'
setw -g window-status-format ' #W '
setw -g window-status-current-format ' #W '
# pane
bind % split-window -h -c "#{pane_current_path}"
bind H select-pane -L
bind L select-pane -R
# use
bind k new-window -c '#{pane_current_path}'
bind -r h previous-window
bind -r l next-window
bind r command-prompt "rename-window '%%'"
bind x kill-window
bind q kill-server
# vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

