# default
set -g prefix C-f
set -g base-index 1
set -g mode-keys vi
set -g default-terminal "xterm-ghostty"
set -as terminal-overrides ",xterm-256color:RGB"
# display
set -g status-position top
set -g status-justify absolute-centre
set -g status-right ''
set -g status-left ''
set -g status-left-length 20
set -g status-style "bg=default"
set -g window-status-style "bg=default,fg=colour250"
set -g window-status-current-style "bg=default,fg=cyan"
# keymap
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

bind u split-window -h -c "#{pane_current_path}"
bind y split-window -h -c "#{pane_current_path}" \;\
       split-window -v -c "#{pane_current_path}" \;\
       select-pane -L

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

