
set -g prefix C-SPACE
# default
set -g base-index 1
set -g mode-keys vi
set -g default-terminal "xterm-ghostty"
set -as terminal-overrides ",xterm-256color:RGB"
# status
set -g status-position top
set -g status-left '*#S'
set -g status-left-length 20
set -g status-style "bg=default"
set -g status-right ''
set -g status-justify absolute-centre
set -g window-status-current-style "bg=default bold"
# pane
bind % split-window -h -c "#{pane_current_path}"
bind H select-pane -L
bind L select-pane -R
# use
bind k new-window -c '#{pane_current_path}'
bind -r h previous-window
bind -r l next-window
bind r command-prompt "rename-window '%%'"
bind x kill-window
bind q kill-server
# vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

